### ISSUE TITLE
TypeError: Florence2Seq2SeqLMOutput.__init__() got an unexpected keyword argument 'loss'

### ISSUE THREAD

**Issue by wavelet2008** [andimarafioti/florence2-finetuning#3]
acefl) ubuntu@ubuntu-X10SRA:~/sdf/florence/florence2-finetuning$ python train.py 
Resolving data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 295373.52it/s]
Loading dataset shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:00<00:00, 14599.23it/s]
Resolving data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 117421.72it/s]
/home/ubuntu/anaconda3/envs/facefl/lib/python3.10/site-packages/transformers/optimization.py:588: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Training Epoch 1/3:   0%|                                                                                                          | 0/9866 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/sdf/florence/florence2-finetuning/train.py", line 151, in <module>
    train_model(train_loader, val_loader, model, processor, epochs=3)
  File "/home/ubuntu/sdf/florence/florence2-finetuning/train.py", line 77, in train_model
    outputs = model(
  File "/home/ubuntu/anaconda3/envs/facefl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/facefl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Florence-2-base-ft/modeling_florence2.py", line 2760, in forward
    return Florence2Seq2SeqLMOutput(
TypeError: Florence2Seq2SeqLMOutput.__init__() got an unexpected keyword argument 'loss'

**Comment by andimarafioti** [comment]
Hi! Could you let me know if you are running the code here without changes? On the train.py file we do:
```python
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Florence-2-base-ft", trust_remote_code=True, revision="refs/pr/6"
).to(device)
```
Which should pull the code from this PR: https://huggingface.co/microsoft/Florence-2-base-ft/discussions/6/files

There, if you look at the changes, you will find that we added the loss argument to Florence2Seq2SeqLMOutput, so this error shouldn't be happening.

**Comment by wavelet2008** [comment]
Thank you very much for your help, the problem has been solved, and I have fine-tuned the model.
