### ISSUE TITLE
finetuning  OD task

### ISSUE THREAD

**Issue by wavelet2008** [andimarafioti/florence2-finetuning#5]
Hi,
Dear author, when can you provide a demo for fine-tuning the OD task? Are there any modifications needed? Thank you very much, I am looking forward to your code

**Comment by andimarafioti** [comment]
I think someone is already working on it, look here: https://github.com/SangbumChoi/florence2-finetuning/commit/863df42ee731a715eed3e188d9844e0702b1fbfe

**Comment by wavelet2008** [comment]
Awesome, thank you very much!
