### ISSUE TITLE
Disuccsion about open vision encoder training

### ISSUE THREAD

**Issue by lucasjinreal** [andimarafioti/florence2-finetuning#8]
Hello, thanks for the wonderful opensoure finetune script. this is the only I found try finetuning on florence rather than use it directly.

However, noticed that you only training llm part, I am wondering, would consider add experiment on open vision encoder finetune?

What I want konw is:

- will open visoin encoder making old knowledge forgetting?
- will open vision encoder able to learn new visual representations in new trainning data?

This is a more interesting topic.

**Comment by andimarafioti** [comment]
Actually, in the distributed_train.py the code also trains the vision encoder. And in the colab, you can train the full model by commenting out the part that sets the vision encoder to not be trainable.

**Comment by lucasjinreal** [comment]
ok I have successfully trained the whole model already
