### ISSUE TITLE
How to finetune on V100

### ISSUE THREAD

**Issue by wjdsg** [andimarafioti/florence2-finetuning#9]
When I run the model, I encountered the question shown in the figure below. How should I solve it?
![image](https://github.com/andimarafioti/florence2-finetuning/assets/59414699/2a7c75fe-102c-4f1b-b4cc-62da3b9ae639)

**Comment by andimarafioti** [comment]
You should run `pip install flash_attn`

**Comment by yuting89830** [comment]
I had run `pip install flash_attn`, but it still output the same error.

**Comment by yuting89830** [comment]
I found that it is because it is incompatible with the cuda and torch versions. 
For the solution, please refer #OrionStarAI/Orion#11
